# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_googleanalytics_sitetitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleanalytics',
            options={'verbose_name': 'Google Analytics Tracking Code', 'verbose_name_plural': 'Google Analytics Tracking Code'},
        ),
    ]
