# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_googleanalytics_sitetitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAnalytics',
        ),
        migrations.DeleteModel(
            name='SiteTitle',
        ),
    ]
