# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_googleanalytics_sitetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedir',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
